export default {
  LANGUAGE: 'en',
  BACK_UI: 'btn btn-secondary',
  BACK_ICON: 'fas fa-arrow-left',
  PAGINATION_UI: 'btn btn-secondary',
  FIRST_ICON: 'fas fa-fast-backward',
  PREVIOUS_ICON: 'fas fa-step-backward',
  NEXT_ICON: 'fas fa-step-forward',
  LAST_ICON: 'fas fa-fast-forward',
  CANCEL_UI: 'btn btn-secondary',
  CANCEL_ICON: 'fas fa-times',
  FILTER_UI: 'btn btn-info',
  FILTER_ICON: 'fas fa-filter',
  GROUP_UI: 'btn btn-warning',
  GROUP_ICON: 'fas fa-th',
  CSV_UI: 'btn btn-secondary csv',
  CSV_ICON: 'fas fa-file-csv',
  CSV_NEW_LINE: '\n',
  CSV_SEPARATOR: '\t',
  CLEAR_UI: 'me-1',
  CLEAR_ICON: 'fas fa-times',
  SORT_UI: 'ms-1',
  SORT_ICON: 'fas fa-sort',
  SORT_ASC_ICON: 'fas fa-sort-down',
  SORT_DESC_ICON: 'fas fa-sort-up',
}
